"""version2

Revision ID: fbade04993f2
Revises: fd0d2b2d2fe0
Create Date: 2022-07-01 00:13:13.710460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbade04993f2'
down_revision = 'fd0d2b2d2fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_other_post_post',type_='foreignkey')
        batch_op.drop_column('reply_post')
        batch_op.drop_column('original_post')
        batch_op.drop_column('is_pulled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pulled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('original_post', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reply_post', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_post_other_post_post', 'post', ['original_post'], ['id'])

    # ### end Alembic commands ###
