"""migration-1

Revision ID: fd0d2b2d2fe0
Revises: 
Create Date: 2022-06-30 14:47:05.630153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0d2b2d2fe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reply_post', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('is_reply', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'post', ['reply_post'], ['id'])
    op.drop_column('post', 'original_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('original_post', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'post', ['original_post'], ['id'])
    op.drop_column('post', 'is_reply')
    op.drop_column('post', 'reply_post')
    # ### end Alembic commands ###
